[build]
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# 重定向規則
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 額外的安全標頭
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# CMS admin 頁面特殊處理
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"